# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_officeConverter(object):
    def setupUi(self, officeConverter):
        officeConverter.setObjectName("officeConverter")
        officeConverter.resize(422, 431)
        self.centralwidget = QtWidgets.QWidget(officeConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.openDirectory = QtWidgets.QPushButton(self.centralwidget)
        self.openDirectory.setGeometry(QtCore.QRect(220, 40, 75, 23))
        self.openDirectory.setObjectName("openDirectory")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.label.setObjectName("label")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.inputPath.setObjectName("inputPath")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(90, 90, 191, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 140, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 61, 21))
        self.label_3.setObjectName("label_3")
        self.launch = QtWidgets.QPushButton(self.centralwidget)
        self.launch.setGeometry(QtCore.QRect(220, 170, 75, 23))
        self.launch.setObjectName("launch")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(90, 220, 211, 131))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 61, 21))
        self.label_4.setObjectName("label_4")
        officeConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(officeConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 22))
        self.menubar.setObjectName("menubar")
        officeConverter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(officeConverter)
        self.statusbar.setObjectName("statusbar")
        officeConverter.setStatusBar(self.statusbar)

        self.retranslateUi(officeConverter)
        QtCore.QMetaObject.connectSlotsByName(officeConverter)

    def retranslateUi(self, officeConverter):
        _translate = QtCore.QCoreApplication.translate
        officeConverter.setWindowTitle(_translate("officeConverter", "OfficeConvert"))
        self.openDirectory.setText(_translate("officeConverter", "打开文件夹"))
        self.label.setText(_translate("officeConverter", "输入文件："))
        self.label_2.setText(_translate("officeConverter", "处理进度："))
        self.comboBox.setItemText(0, _translate("officeConverter", "Pdf转Word"))
        self.comboBox.setItemText(1, _translate("officeConverter", "Word转Pdf"))
        self.label_3.setText(_translate("officeConverter", "功能选择："))
        self.launch.setText(_translate("officeConverter", "转换"))
        self.label_4.setText(_translate("officeConverter", "输出信息:"))
